# Define custom Docker networks
networks:
  project-network:

# Define services for the application
services:

  # PHP service configuration
  php:
    build:
      # Path to the build context
      context: .
      # Dockerfile for PHP
      dockerfile: docker/php/Dockerfile
    # Image name
    image: php83-fpm-alpine
    # Name of the container
    container_name: php
    # Restart policy
    restart: unless-stopped
    # Set the working directory inside the container
    working_dir: /app
    volumes:
      # Bind the project directory to the container
      - ./project:/app
      # Map PHP logs to the host system for debugging
      - ./logs/php:/var/log/php
    # Environment variable for application configuration
    environment:
      APP_ENV: local
    # Attach to the custom network
    networks:
      - project-network
    # Run Composer and start PHP-FPM
    command: sh -c "composer install && php-fpm"

  # Nginx service configuration
  nginx:
    build:
      # Path to the build context
      context: .
      # Dockerfile for Nginx
      dockerfile: docker/nginx/Dockerfile
    # Image name
    image: nginx-alpine
    # Name of the container
    container_name: nginx
    # Restart policy
    restart: unless-stopped
    # Map container port 80 to host port 8000
    ports:
      - "8000:80"
    volumes:
      # Bind the project directory to the container
      - ./project:/app
      # Map Nginx logs to the host system for debugging
      - ./logs/nginx:/var/log/nginx
    # Ensure the PHP service starts first
    depends_on:
      - php
    # Attach to the custom network
    networks:
      - project-network

  postgres:
    build:
      # Путь к build context
      context: .
      # Путь к Dockerfile для PostgreSQL
      dockerfile: docker/postgres/Dockerfile
    # Имя создаваемого образа
    image: postgres:17-alpine
    # Имя контейнера
    container_name: postgres
    # Политика перезапуска
    restart: unless-stopped
    # Настройки для монтирования данных
    volumes:
      # Хранение данных PostgreSQL на хосте
      - ./data/postgres:/var/lib/postgresql/data
      # Логи PostgreSQL
      - ./logs/postgres:/var/log/postgresql
    # Настройка переменных окружения
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
      PGDATA: /var/lib/postgresql/data/db
    ports:
      - "5432:5432"
    # Подключение к сети
    networks:
      - project-network